Team = {'Co-ordinators': [['Dhruvi Vadalia',
                    'Co-ordinator',
                    'GitHub: @diggy-19',
                    'https://github.com/diggy-19',
                    'Codechef: @python_c99',
                    'https://www.codechef.com/users/python_c99'],
                   ['Karan Sheth',
                    'Co-ordinator',
                    'GitHub: @Korusuke',
                    'https://github.com/Korusuke',
                    'Codechef: @Karan1599',
                    'https://www.codechef.com/users/Karan1599'],
                   ['Aditya Prajapati',
                    'Co-ordinator',
                    'GitHub: @aditya1999',
                    'https://github.com/aditya1999',
                    'Codechef: @C0DE_BL00DED',
                    'https://www.codechef.com/users/c0de_blooded']],
 'Committee Head': [['Chirag Shetty',
                     'Committee Head',
                     'GitHub: @nurdtechie98',
                     'https://github.com/nurdtechie98',
                     'Codechef: @nurdtechie98',
                     'https://www.codechef.com/users/nurdtechie98'],
                     ['Nishchith Shetty',
                     'Committee Head',
                     'GitHub: @inishchith',
                     'https://github.com/inishchith',
                     'Codechef: @inishchith',
                     'https://www.codechef.com/users/inishchith']],
 'Creative Team': [['Sangram Desai',
                    'Creative Team',
                    'GitHub: @Sangramdesai123',
                    'https://github.com/sangramdesai123',
                    'Codechef: @Sangram123',
                    'https://www.codechef.com/users/sangram123'],
                   ['Shivanee Jaiswal',
                    'Creative Team',
                    'GitHub: @shivaneej',
                    'https://github.com/shivaneej',
                    'Codechef: @shivanee_j',
                    'https://www.codechef.com/users/shivanee_j']],
 'PR Team': [['Hetal Kuvadia',
              'PR Team',
              'GitHub: @hetzz',
              'https://github.com/hetzz',
              'Codechef: @hetal_kuvadia',
              'https://www.codechef.com/users/hetal_kuvadia1'],
             ['Sana Pagarkar',
              'PR Team',
              'GitHub: @sanapagarkar',
              'https://github.com/sanapagarkar',
              'Codechef: @sana905',
              'https://www.codechef.com/users/sana905']],
 'Technical Team': [['Neel Shah',
                     'Tech Head',
                     'GitHub: @Freelancer-98',
                     'https://github.com/Freelancer-98',
                     'Codechef: @shmabulock',
                     'https://www.codechef.com/users/shmabulock'],
                    ['Shivam Pawase',
                     'Tech team',
                     'GitHub: @shivam1708',
                     'https://github.com/shivam1708',
                     'Codechef: @shivam_1708',
                     'https://www.codechef.com/users/shivam_1708'],
                    ['Devansh Solanki',
                     'Tech Team',
                     'GitHub: @devanshsnlk',
                     'https://github.com/devanshslnk',
                     'Codechef: @devanshslnk',
                     'https://www.codechef.com/users/devanshslnk'],
                    ['Tushar Kadam',
                     'Tech Team',
                     'GitHub: @Kadam-Tushar',
                     'https://github.com/Kadam-Tushar',
                     'Codechef: @cis_pie',
                     'https://www.codechef.com/users/cis_pie'],
                    ['Akshay Padte',
                     'Tech Team',
                     'GitHub: @akshay-99',
                     'https://github.com/akshay-99',
                     'Codechef: @akshay_07cf',
                     'https://www.codechef.com/users/akshay_07cf'],
                    ['Rushang Gajjal',
                     'Tech Team',
                     'GitHub: @RusherRG',
                     'https://github.com/RusherRG',
                     'Codechef: @RusherRG',
                     'https://www.codechef.com/users/rusherrg']]}


import pickle

with open('data/team.pkl','wb') as f:
    pickle.dump(Team,f, pickle.HIGHEST_PROTOCOL)



'''Faculty Advisors': [['Deepti Pawade',
                       'Faculty Advisor',
                       'Information Technology, KJSCE',
                       'https://www.somaiya.edu/kjsce/academic/faculty/0000160863/ms__dipti_yogesh_pawade/0#Personal_Profile'],
                      ['Grishma Sharma',
                       'Faculty Advisor',
                       'Computer Department, KJSCE',
                       'https://www.somaiya.edu/kjsce/academic/faculty/0000160102/mrs__grishma_jaideep_sharma/0#Personal_Profile']],
'''